[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"

[phases.start] 
cmd = "npm start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"