[phases.setup]
nixPkgs = ["python", "pip"]

[phases.install]
cmd = "echo 'Backend installation'"

[phases.build]
cmd = "echo 'Backend build'"

[phases.start] 
cmd = "echo 'Backend start'"

[variables]
NODE_ENV = "production"